security:
    encoders:
        App\Entity\User:
          algorithm: bcrypt

    providers:
        database_users:
          entity:
            class: App:User
            property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            pattern: ^/
            guard:
                authenticator:
                    - App\Security\LoginAuthenticator
            logout_on_user_change: true

            logout:
              path: /logout
              target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
