version: '2'

services:
  blog-server:
    build: ./docker/php
    image: blog-symfony
    links:
      - mysql
    volumes:
      - ./:/application
      - /application/var/sessions/

  mysql:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony-blog
    volumes:
      - ./tmp/db:/var/lib/mysql

  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/application
    links:
      - blog-server
