version: '3'

services:
  blog-server:
    build: ./docker/php
    image: blog-symfony
    depends_on:
      - db
    volumes:
      - ./:/application:cached
      - /application/var/sessions/

  db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony-blog
    volumes:
      - ./tmp/db:/var/lib/mysql

  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/application:cached
    depends_on:
      - blog-server

