security:
    encoders:
        AppBundle\Entity\User:
          algorithm: bcrypt

    providers:
        database_users:
          entity:
            class: AppBundle:User
            property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern: ^/
            http_basic: ~
            provider: database_users

    access_control:
        - { path: ^/admin, role: ROLE_ADMIN }
