parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
          - { name: twig.extension }

    AppBundle\Subscribers\UploadSubscriber:
        tags:
          - { name: doctrine.event_subscriber, connection: default }

    AppBundle\Services\FileUploader:
        arguments:
          $targetDir: '%image_articles_coverages_directory%'

    AppBundle\Services\Paginator:
        arguments:
          $itemPerPage: '%itemperpage%'
